### ISSUE TITLE
added copper blocks to your resource pack

### ISSUE THREAD

**Issue by leevee123** [abbydiode/half-mine#5]
[Half-Mine_copper.zip](https://github.com/user-attachments/files/16323574/Half-Mine_copper.zip)
dont know how to contact you, but i updated your resource pack to include copper blocks and copper grates to use metal1-4 and grate1-4 thought you might want to know

**Comment by abigailwillow** [comment]
Hi! My contact details should be public on my profile. Could you open a [PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) for this change so that I can properly review the changes and credit you appropriately?
